<?php
/***************************************************************************
 *                          lang_faq.php [finnish]
 *                            -------------------
 *   begin                : Sunday Dec 24, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_faq.php,v 1.1 2004/07/27 20:01:09 akamu Exp $
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/

//
//	Translation produced by Jorma Aaltonen (bullitt)
//	http://www.pitro.com/
//


// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\";
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//
 
  
$faq[] = array("--","Kirjautuminen ja rekister&ouml;ityminen");
$faq[] = array("Miksi en voi kirjautua sis&auml;&auml;n?", "Oletko rekister&ouml;itynyt? Ihan tosi, sinun t&auml;ytyy rekister&ouml;ity&auml; voidaksesi kirjautua sis&auml;&auml;n. Onko sinulla porttikielto j&auml;rjestelm&auml;&auml;n(mik&auml;li on, t&auml;st&auml; n&auml;ytet&auml;&auml;n viesti sinulle)? Mik&auml;li n&auml;in on, sinun t&auml;ytyy ottaa yhteytt&auml; j&auml;rjestelm&auml;n yll&auml;pitoon tai  webmasteriin selvitt&auml;&auml;ksesi syyn. Jos olet rekister&ouml;itynyt, etk&auml; ole porttikiellossa, etk&auml; silti voi kirjautua sis&auml;&auml;n tarkista viel&auml; kerran k&auml;ytt&auml;j&auml;tunnus ja salasana. Yleens&auml; ongelma on n&auml;iss&auml;. Mik&auml;li ei, niin ota yhteytt&auml; j&auml;rjestelm&auml;n yll&auml;pitoon, heill&auml; voi olla v&auml;&auml;r&auml;t asetukset j&auml;rjestelm&auml;ss&auml;.");
$faq[] = array("Miksi en voi rekister&ouml;ity&auml;?", "Ehk&auml; sinun ei tarvitsekaan. J&auml;rjestelm&auml;n yll&auml;pit&auml;j&auml; m&auml;&auml;rittelee t&auml;ytyyk&ouml; rekister&ouml;ity&auml; voidakseen kirjoittaa viestej&auml;. Rekister&ouml;inti antaa kuitenkin k&auml;ytt&ouml;&ouml;si lis&auml;ominaisuuksa, kuten m&auml;&auml;ritelt&auml;v&auml;t avatar kuvat, yksityisviestit, s&auml;hk&ouml;postin l&auml;hetys muille k&auml;ytt&auml;jille, k&auml;ytt&auml;j&auml;ryhmiin liittyminen, jne. Rekister&ouml;ityminen vie vain hetken ja se on suositeltavaa.");
$faq[] = array("Miksi kirjaudun ulos automaattisesti?", "Jos et laita rastia <i>Kirjaa minut sis&auml;&auml;n automaattisesti</i> laatikkoon kirjautuessasi sis&auml;&auml;n, pysyt kirjautuneena vain ennalta s&auml;&auml;detyn ajan. N&auml;in estet&auml;&auml;n k&auml;ytt&auml;j&auml;tunnuksesi luvaton k&auml;ytt&ouml;. Pysy&auml;ksesi kirjautuneena rastita laatikko kirjautumisen yhteydess&auml;. T&auml;m&auml; ei ole suositeltavaa jos samaa yhteytt&auml;/tietokonetta k&auml;ytt&auml;v&auml;t muutkin k&auml;ytt&auml;j&auml;t esim. kirjasto, internet kahvila, oppilaitoksen koneet, jne.");
$faq[] = array("Kuinka voin est&auml;&auml; k&auml;ytt&auml;j&auml;tunnukseni n&auml;kymisen sen hetkisten k&auml;ytt&auml;jien listalla?", "K&auml;ytt&auml;j&auml;tiedoissasi on optio <i>Piilota online status</i>, jos k&auml;yt&auml;t t&auml;ss&auml; <i>kyll&auml;</i> n&auml;yt vain j&auml;rjestelm&auml;n yll&auml;pit&auml;j&auml;lle ja itsellesi. Sinut lasketaan piilossa olevaksi k&auml;ytt&auml;j&auml;ksi.");
$faq[] = array("Unohdin salasanani!", "Ei paniikkia! Vaikka salasanaasi ei voi selvitt&auml;&auml;, se voidaan resetoida. Tehd&auml;ksesi t&auml;m&auml;n siirry kirjautumissivulle ja klikkaa <u>Unohdin salasanani</u>, seuraa ohjeita ja ongelma on tuota pikaa hoidettu.");
$faq[] = array("Rekister&ouml;idyin mutta en voi kirjautua!", "Tarkista ensin, ett&auml; k&auml;yt&auml;t oikeaa k&auml;ytt&auml;j&auml;tunnusta ja salasanaa. Jos ne ovat kunnossa, niin on kaksi todenn&auml;k&ouml;ist&auml; vaihtoehtoa. Jos COPPA tuki on p&auml;&auml;ll&auml; ja klikkasit<u>Olen alle 18 vuotta</u> linkki&auml; rekister&ouml;ityess&auml;si joudut seuraamaan saamiasi ohjeita. Jos kyse ei ole  t&auml;st&auml;, niin tarvitseeko k&auml;ytt&auml;j&auml;tunnuksesi aktivoinnin? Jotkin j&auml;rjestlm&auml;t vaativat jokaisen uuden k&auml;ytt&auml;j&auml;n erillisen aktivoinnin joko k&auml;ytt&auml;j&auml;n toimesta tai yll&auml;pit&auml;j&auml;n toimesta. Rekister&ouml;ityess&auml;si sait tiedon siit&auml; vaaditaanko aktivointi. Mik&auml;li sait s&auml;hk&ouml;postia, noudata sen ohjeita. Jos et saanut s&auml;hk&ouml;postia, oletko varma, ett&auml; annoit oikean s&auml;hk&ouml;postiosoitteen? Yksi syy, miksi erillist&auml; aktivointia k&auml;ytet&auml;&auml;n on  <i>t&ouml;rkeiden</i> k&auml;ytt&auml;jien karsiminen est&auml;m&auml;ll&auml; anonyymi k&auml;ytt&ouml;. Jos olet varma, ett&auml; antamasi s&auml;hk&ouml;&ouml;ostiosoite oli oikein, ota yhteys j&auml;rjestelm&auml;n yll&auml;pitoon.");
$faq[] = array("Rekister&ouml;idyin kauan sitten mutta en p&auml;&auml;se en&auml;&auml; kirjautumaan?!", "Yleisimm&auml;t syyt t&auml;h&auml;n ovat; annoit v&auml;&auml;r&auml;n k&auml;ytt&auml;j&auml;tunnuksen tai salasanan (tarkista s&auml;hk&ouml;postistasi tiedot jotka sait kun rekister&ouml;idyit) tai yll&auml;pito on poistanut k&auml;ytt&auml;j&auml;tunnuksesi jostain syyst&auml;. J&auml;lkimm&auml;isess&auml; tapauksessa et ehk&auml; ole kirjoittanut mit&auml;&auml;n? On yleist&auml;, ett&auml; j&auml;rjestelm&auml;t poistavat k&auml;ytt&auml;ji&auml;, jotka eiv&auml;t ole kirjoittaneet mit&auml;&auml;n. N&auml;in pidet&auml;&auml;n tietokantaa siistimp&auml;n&auml;. Yrit&auml; rekister&ouml;ity&auml; uudestaan ja ota osaa keskusteluihin.");


$faq[] = array("--","K&auml;ytt&auml;j&auml;tiedot ja asetukset");
$faq[] = array("Kuinka muutan asetuksiani?", "Kaikki asetuksesi (jos olet rekister&ouml;itynyt) ovat tietokannassa. Muuttaaksesi tietojasi klikkaa  <u>K&auml;ytt&auml;j&auml;tiedot</u> linkki&auml; (yleens&auml; sivun yl&auml;reunassa mutta ei v&auml;ltt&auml;m&auml;tt&auml; aina). N&auml;in p&auml;&auml;set muuttamaan kaikkia asetuksiasi.");
$faq[] = array("Ajat eiv&auml;t ole oikein!", "Ajat ovat melko varmasti oikein, saatat kuitenkin n&auml;hd&auml; ajat eri aikavy&ouml;hykkeelt&auml; kuin miss&auml; olet. Mik&auml;li kyse on t&auml;st&auml; t&auml;ytyy sinun muuttaa k&auml;ytt&auml;j&auml;tiedoissasi aikavy&ouml;hykett&auml; vastaamaan oikeaa aluetta. Huomaa, ett&auml; aikavy&ouml;hykkeen muuttaminen, kuten useimmat asetukset, on mahdollista vain rekister&ouml;idyille k&auml;ytt&auml;jille. Joten jos et ole rekister&ouml;itynyt, nyt on hyv&auml; hetki rekister&ouml;ity&auml;.");
$faq[] = array("Muutin aikavy&ouml;hykett&auml; ja ajat ovat silti v&auml;&auml;rin!", "Jos olet varma, ett&auml; aikavy&ouml;hyke on oikein ja aika on silti eri, niin todenn&auml;k&ouml;isin vaihtoehto on kes&auml;ajan k&auml;ytt&ouml;. J&auml;rjestelm&auml;&auml; ei ole suunniteltu ottamaan huomioon talvi- ja kes&auml;ajan vaihteluita joten kes&auml;ll&auml; aika voi olla tunnin eri kuin normaali paikallinen aika.");
$faq[] = array("Kieleni ei ole listalla!", "Todenn&auml;k&ouml;isesti yll&auml;pito ei ole asentanut kielivaihtoehtoasi tai kukaan ei ole tehnyt tarvittavaa k&auml;&auml;nn&ouml;st&auml;. Kysy yll&auml;pidolta voivatko he asentaa tarvittavan kielipaketin. Jos sellaista ei ole, voit vapaasti luoda uuden k&auml;&auml;nn&ouml;ksen. Lis&auml;tietoja l&ouml;ytyy phpBB ryhm&auml;n web sivuilta (Linkki sivujen alareunassa)");
$faq[] = array("Kuinka saan kuvan k&auml;ytt&auml;j&auml;tunnukseni alle?", "K&auml;ytt&auml;j&auml;tunnuksen alla voi olla kaksi kuvaa katsottaessa viestej&auml;. Ensimm&auml;inen on kuva joka on liitetty titteliisi, yleens&auml; rivi t&auml;hti&auml; kuvaamassa kuinka monta viesti&auml; olet l&auml;hett&auml;nyt tai mik&auml; on statuksesi j&auml;rjestelm&auml;ss&auml;. T&auml;m&auml;n alla voi olla isompi kuva, avatar, t&auml;m&auml; on yleens&auml; henkil&ouml;kohtainen jokaisella k&auml;ytt&auml;j&auml;ll&auml;. J&auml;rjestelm&auml;n yll&auml;pit&auml;j&auml;st&auml; riippuu, ovatko avatarit sallittuja ja kuinka avatarit tuodaan n&auml;ht&auml;v&auml;ksi. Jos et voi k&auml;ytt&auml;&auml; avatarta, niin kyse on yll&auml;pit&auml;j&auml;n ratkaisusta. Voit kysy&auml; heilt&auml; syyt&auml; t&auml;h&auml;n (Syyt ovat varmasti hyv&auml;t!)");
$faq[] = array("Kuinka muutan titteli&auml;ni?", "Yleens&auml; et voi muuttaa mit&auml;&auml;n titteli&auml; (titteli n&auml;kyy k&auml;ytt&auml;j&auml;tunnuksesi alapuolella viesteiss&auml; ja k&auml;ytt&auml;j&auml;tiedoissasi k&auml;ytetyst&auml; tyylist&auml; riippuen). Useimmat j&auml;rjestelm&auml;t rankkaavat k&auml;ytt&auml;j&auml;t l&auml;hetettyjen viestien m&auml;&auml;r&auml;n mukaan tai osoittamaan tietty&auml; k&auml;ytt&auml;j&auml;tyyppi&auml;, esim. moderaattoreilla ja yll&auml;pit&auml;jill&auml; voi olla omat erikoistittelit. Ole hyv&auml; &auml;l&auml;k&auml; turhaan rasita j&auml;rjestelm&auml;&auml; kirjoittamalla tarpeettomia viestej&auml; vain korottaaksesi titteli&auml;si, todenn&auml;k&ouml;isesti t&auml;ll&ouml;in yll&auml;pito tai moderaattori pienent&auml;&auml; viestiesi m&auml;&auml;r&auml;&auml;.");
$faq[] = array("Kun klikkaan k&auml;ytt&auml;j&auml;n s&auml;hk&ouml;postilinkki&auml;, pyydet&auml;&auml;n kirjautumaan sis&auml;&auml;n?", "Valitettavasti vain rekister&ouml;idyt k&auml;ytt&auml;j&auml;t voivat l&auml;hett&auml;&auml; s&auml;hk&ouml;postia sis&auml;&auml;nrakennetulla s&auml;hk&ouml;postilomakkeella (Jos yll&auml;pito on sallinut t&auml;m&auml;n ominaisuuden). N&auml;in estet&auml;&auml;n asiattomien k&auml;ytt&auml;jien anonyymi j&auml;rjestelm&auml;n hyv&auml;ksik&auml;ytt&ouml;.");


$faq[] = array("--","Viestien kirjoitukseen liittyv&auml;t aiheet");
$faq[] = array("Kuinka luon aiheen foorumiin?", "Helppoa, klikkaa vastaavaa painiketta joko foorumin tai aiheen ikkunassa. Voi olla, ett&auml; sinun t&auml;ytyy rekister&ouml;ity&auml; ennen kuin voit kirjoittaa viestin. Toimintamahdollisuutesi on lueteltu foorumin ja aiheen sivuilla (Eli <i>Voit luoda uusia aiheita, Voit &auml;&auml;nest&auml;&auml; &auml;&auml;nestyksiss&auml;, jne.<i> lista)");
$faq[] = array("Kuinka muokkaan tai poistan viestin?", "Jollet ole yll&auml;pit&auml;j&auml; tai foorumin moderaattori voi muokata ja poistaa vain omia viestej&auml;si. Voit muokata viesti&auml; (joskus vain rajoitetun ajan luonnin j&auml;lkeen) klikkaamalla <i>muokkaa</i> painiketta kyseisell&auml; viestill&auml;.  Jos joku on jo vastannut viestiin n&auml;et pienen palan teksti&auml; viestin alapuolella kun palaat aiheeseen, n&auml;in listataan kuinka monta kertaa olet muokannut viesti&auml;. T&auml;m&auml; ei n&auml;y jos kukaan ei ole vastannut, se ei n&auml;y my&ouml;sk&auml;&auml;n jos moderaattori tai yll&auml;pito on muokannut viesti&auml; (heid&auml;n tulisi j&auml;tt&auml;&auml; tieto, mit&auml; he ovat muokanneet ja miksi). Huomaa, ett&auml; tavalliset k&auml;ytt&auml;j&auml;t eiv&auml;t voi poistaa viesti&auml; jos siihen on vastattu.");
$faq[] = array("Kuinka lis&auml;&auml;n allekirjoituksen viestiini?", "Voidaksesi lis&auml;t&auml; allekirjoituksen, on sinun ensin luotava sellainen. T&auml;m&auml; tapahtuu k&auml;ytt&auml;j&auml;tietojesi kautta. Luotuasi allekirjoituksen voit laittaa rastin <i>Lis&auml;&auml; allekirjoitus</i> laatikkoon postituslomakkeella lis&auml;t&auml;ksesi allekirjoituksen. Voit my&ouml;s m&auml;&auml;ritell&auml; allekirjoituksen tulevan oletusarvoisesti kaikkiin viesteihisi laittamalla raksin asianomaiseen valintalaatikkoon k&auml;ytt&auml;j&auml;tiedoissasi (voit silti est&auml;&auml; allekirjoituksen yksitt&auml;isist&auml; viesteist&auml; poistamalla raksin lis&auml;&auml; allekirjoitus laatikosta postituslomakkeella)");
$faq[] = array("Kuinka luon &auml;&auml;nestyksen?", "&AUML;&auml;nestyksen luonti on helppoa. Kun luot uuden aiheen (tai muokkaat aiheen ensimm&auml;ist&auml; viesti&auml;, jos sinulla on oikeus) sinun pit&auml;isi n&auml;hd&auml; <i>Lis&auml;&auml; &auml;&auml;nestys</i> lomake postituslomakkeen alapuolella (jos t&auml;t&auml; ei tule n&auml;kyviin, sinulla ei todenn&auml;k&ouml;isesti ole oikeutta luoda &auml;&auml;nestyksi&auml;). Anna &auml;&auml;nestykselle otsikko ja v&auml;hint&auml;&auml;n kaksi vaihtoehtoa (aseta vaihtoehto klikkaamlla <i>Lis&auml;&auml; vaihtoehto</i> painiketta. Voit my&ouml;s asettaa aikarajoituksen &auml;&auml;nestykselle, 0 on ikuinen &auml;&auml;nestys. J&auml;rjestelm&auml;n yll&auml;pit&auml;j&auml; on m&auml;&auml;ritellyt &auml;&auml;nestyksen vaihtoehdoille yl&auml;rajan.");
$faq[] = array("Kuinka muokkaan tai poistan &auml;&auml;nestyksen?", "Kuten viesteiss&auml;kin, &auml;&auml;nestyksi&auml; voi muokata vain alkuper&auml;inen postittaja, moderaattori tai j&auml;rjestelm&auml;n yll&auml;pit&auml;j&auml;. Muokataksesi &auml;&auml;nestyst&auml; klikkaa aiheen ensimm&auml;ist&auml; viesti&auml; (&auml;&auml;nestys on aina liitetty t&auml;h&auml;n viestiin). Jos kukaan ei ole viel&auml; &auml;&auml;nest&auml;nyt voi k&auml;ytt&auml;j&auml; poistaa &auml;&auml;nestyksen tai muokata &auml;&auml;nestyksen vaihtoehtoja. Jos &auml;&auml;ni&auml; on jo annettu vain moderaattori tai j&auml;rjestelm&auml;n yll&auml;pit&auml;j&auml; voivat muokata tai poistaa &auml;&auml;nestyksen. N&auml;in estet&auml;&auml;n k&auml;ytt&auml;ji&auml; manipuloimasta &auml;&auml;nestyksi&auml; vaihtamalla vaihtoehtoja kesken &auml;&auml;nestyksen");
$faq[] = array("Miksi en p&auml;&auml;se foorumiin?", "Jotkin foorumit voivat olla rajoitettuja tietyille k&auml;ytt&auml;jille tai k&auml;ytt&auml;j&auml;ryhmille. Voidaksesi n&auml;hd&auml;, lukea, kirjoittaa jne. saatat tarvita erikoisluvan. Vain foorumin moderaattori ja j&auml;rjestelm&auml;n yll&auml;pit&auml;j&auml; voivat my&ouml;nt&auml;&auml; luvan, ota yhteys heihin.");
$faq[] = array("Miksi en voi &auml;&auml;nest&auml;&auml;?", "Vain rekister&ouml;idyt k&auml;ytt&auml;j&auml; voivat &auml;&auml;nest&auml;&auml; (n&auml;in estet&auml;&auml;n tulosten ved&auml;tys). Jos olet rekister&ouml;itynyt, etk&auml; silti voi &auml;&auml;nest&auml;&auml; sinulla todenn&auml;k&ouml;isesti ei ole riitt&auml;vi&auml; oikeuksia.");


$faq[] = array("--","Muotoilut ja aihetyypit");
$faq[] = array("Mit&auml; on BBCode?", "BBCode erityinen variaatio HTML:st&auml;. Yll&auml;pito on m&auml;&auml;ritellyt voitko k&auml;ytt&auml;&auml; BBCode:a (voit my&ouml;s itse est&auml;&auml; sen viestikohtaisesti viestilomakkeella). BBCode muistuttaa HTML:&auml;&auml;. Tagit ymp&auml;r&ouml;id&auml;&auml;n hakasuluilla [ ja ] ja tyyli antaa paremman mahdollisuuden m&auml;&auml;ritt&auml;&auml; miten jokin asia esitet&auml;&auml;n. Saadaksesi lis&auml;tietoa BBCode:sta katso opasta, johon p&auml;&auml;see viestilomakkeelta.");
$faq[] = array("Voinko k&auml;ytt&auml;&auml; HTML:&auml;&auml;?", "T&auml;m&auml; riippuu siit&auml; salliiko yll&auml;pito t&auml;m&auml;n. Yll&auml;pito m&auml;&auml;r&auml;&auml; t&auml;st&auml; t&auml;ysin. Jos sinun sallitaan k&auml;ytt&auml;&auml; sit&auml;, huomaat todenn&auml;k&ouml;isesti vain osan tageista toimvan. T&auml;m&auml; johtuu <i>turvallisuussyist&auml;</i>. N&auml;in estet&auml;&auml;n k&auml;ytt&auml;ji&auml; sotkemasta j&auml;rjestelm&auml;&auml; k&auml;ytt&auml;m&auml;ll&auml; tageja, jotka tuhoavat asettelun tai aiheuttavat muita ongelmia. Jos HTML on sallittua, voit est&auml;&auml; sen k&auml;yt&ouml;n viestikohtaisesti viestilomakkeella.");
$faq[] = array("Mit&auml; ovat hymi&ouml;t?", "Hymi&ouml;t tai  Emoticonit ovat pieni&auml; kuvakkeita joilla voidaan viestitt&auml;&auml; tuntemuksia k&auml;ytt&auml;m&auml;ll&auml; lyhytt&auml; koodia, esim. :) tarkoittaa iloista, :( tarkoittaa surullista. Koko listan emoticoneista n&auml;et viestilomakkeen kautta. &AUML;l&auml; ylik&auml;yt&auml; hymi&ouml;it&auml;, ne voivat muuttaa viestisi huonosti luettavaksi ja moderaattori voi muuttaa niit&auml; tai poistaa kokonaan.");
$faq[] = array("Voinko lis&auml;t&auml; kuvia viesteihin?", "Kuvia voidaan lis&auml;t&auml; viesteihin. T&auml;ll&auml; hetkell&auml; ei kuitenkaan ole menetelm&auml;&auml; siirt&auml;&auml; kuvia suoraan j&auml;rjestelm&auml;&auml;n. Siksi joudut k&auml;ytt&auml;m&auml;&auml;n linkki&auml; kuvatiedostoon yleisesti k&auml;yt&ouml;ss&auml; olevan serverin kautta, esim. http://www.jokin-outo-paikka.net/omakuva.gif. Et voi linkitt&auml;&auml; kuvia, jotka ovat omalla PC:ll&auml;si (ellei se ole julkisesti k&auml;yt&ouml;ss&auml; oleva serveri) eik&auml; kuva voi olla kirjautumismekanismin takana, esim. hotmail tai yahoo s&auml;hk&ouml;postit, salasanalla suojatut sivut, jne. N&auml;ytt&auml;&auml;ksesi kuvan k&auml;yt&auml; joko BBCodea [img] tagi tai vastaava HTML tagi (jos sallittu).");
$faq[] = array("Mit&auml; ovat ilmoitukset?", "Ilmoitus sis&auml;lt&auml;&auml; usein t&auml;rke&auml;&auml; tietoa ja sinun tulisi lukea ne niin pian kuin mahdollista. Ilmoitukset n&auml;kyv&auml;t asianomaisten foorumien joka sivun yl&auml;reunassa. Se voitko luoda ilmoituksia riippuu tarvittavista oikeuksista, jotka m&auml;&auml;rittelee yll&auml;pito.");
$faq[] = array("Mit&auml; ovat tiedotukset?", "Tiedotukset n&auml;kyv&auml;t Ilmoitusten alapuolella k&auml;yt&ouml;ss&auml; olevalla foorumilla ja vain foorumin ensimm&auml;isell&auml; sivulla. Ne ovat usein eritt&auml;in t&auml;rkeit&auml;, joten sinun tulisi lukea ne aina kun mahdollista. Kuten ilmoituksissakin yll&auml;pito m&auml;&auml;rittelee millaisilla oikeuksilla voidaan luoda tiedotteita foorumikohtaisesti.");
$faq[] = array("Mit&auml; ovat lukitut aiheet?", "Aiheen lukitsee joko moderaattori tai yll&auml;pito. Lukittuun aiheeseen ei voi vastata ja mahdollinen &auml;&auml;nestys on automaattisesti p&auml;&auml;ttynyt. Aiheita voidaan lukita monista eri syist&auml;.");


$faq[] = array("--","K&auml;ytt&auml;j&auml;tasot ja ryhm&auml;t");
$faq[] = array("Keit&auml; ovat yll&auml;pit&auml;j&auml;t?", "Yll&auml;pit&auml;j&auml;t ovat henkil&ouml;it&auml;, joilla on korkeimmat k&auml;ytt&ouml;oikeudet koko j&auml;rjestelm&auml;ss&auml;. N&auml;m&auml; k&auml;ytt&auml;j&auml;t voivat kontrolloida kaikkia j&auml;rjestelm&auml;n tapahtumia, mukaan lukien oikeuksien asettaminen, porttikiellot, k&auml;ytt&auml;j&auml;ryhmien ja moderaattorien luonti, jne. Heill&auml; on my&ouml;s t&auml;ydet moderointioikeudet kaikissa foorumeissa.");
$faq[] = array("Keit&auml; ovat moderaattorit?", "Moderaattorit ovat henkil&ouml;it&auml; (tai ryhm&auml; henkil&ouml;it&auml;) joiden teht&auml;v&auml;n&auml; on valvoa foorumeita p&auml;ivitt&auml;in. Heill&auml; on oikeus muokata tai poistaa viestej&auml;, lukita, vapauttaa, siirt&auml;&auml;, poistaa ja jakaa aiheita siin&auml; foorumissa, jossa he ovat moderaattorina. Yleens&auml; moderaattorin teht&auml;v&auml;n&auml; on hillit&auml; kirjoittajia jotka  <i>eiv&auml;t pysy aiheessa<i> tai k&auml;ytt&auml;v&auml;t paheksuttavaa materiaalia.");
$faq[] = array("Mit&auml; ovat k&auml;ytt&auml;j&auml;ryhm&auml;t?", "K&auml;ytt&auml;j&auml;ryhmill&auml; yll&auml;pito j&auml;rjestelee k&auml;ytt&auml;ji&auml;. Jokainen k&auml;ytt&auml;j&auml; voi kuulua useaan ryhm&auml;&auml;n (t&auml;m&auml; poikkeaa useimmista muista vastaavista j&auml;rjestelmist&auml;) ja jokaiselle ryhm&auml;lle voidaan my&ouml;nt&auml;&auml; omat oikeutensa. N&auml;in yll&auml;pidon on helppo m&auml;&auml;ritt&auml;&auml; usea henkil&ouml; yhdell&auml; kertaa foorumin moderaattoriksi tai antaa heille oikeus p&auml;&auml;st&auml; yksityiseen foorumiin jne.");
$faq[] = array("Kuinka liityn k&auml;ytt&auml;j&auml;ryhm&auml;&auml;n?", "Liitty&auml;ksesi k&auml;ytt&auml;j&auml;ryhm&auml;&auml;n klikkaa k&auml;ytt&auml;j&auml;ryhm&auml;n linkki&auml; sivun yl&auml;reunassa (paikka riippuvainen k&auml;ytett&auml;v&auml;st&auml; tyylist&auml;), sivulla voit tarkastella kaikkia k&auml;ytt&auml;j&auml;ryhmi&auml;. Kaikkiin ryhmiin ei ole <i>vapaata p&auml;&auml;sy&auml;</i>, jotkin ryhm&auml;t ovat suljettuja ja osa my&ouml;s piilotettuja. Jos ryhm&auml; on avoin, voit pyyt&auml;&auml; ryhm&auml;n j&auml;senyytt&auml; klikkaamalla vastaavaa painiketta. K&auml;ytt&auml;j&auml;ryhm&auml;n moderaattorin tulee hyv&auml;ksy&auml; hakemuksesi. H&auml;n saattaa kysy&auml;, miksi haluat liitty&auml; ryhm&auml;&auml;n. Ole hyv&auml; &auml;l&auml;k&auml; h&auml;irik&ouml;i moderaattoria jos h&auml;n ei hyv&auml;ksy hakemustasi. Heill&auml; on syyns&auml;.");
$faq[] = array("Kuinka p&auml;&auml;sen k&auml;ytt&auml;j&auml;ryhm&auml;n moderaattoriksi?", "K&auml;ytt&auml;j&auml;ryhm&auml;n luo alunperin yll&auml;pito, joka my&ouml;s m&auml;&auml;r&auml;&auml; ryhm&auml;n moderaattorin. Jos olet halukas perustamaan k&auml;ytt&auml;j&auml;ryhm&auml;n ota ensin yhteytt&auml; yll&auml;pitoon. Yrit&auml; j&auml;tt&auml;&auml; heille yksityisviesti.");


$faq[] = array("--","Yksityiset viestit");
$faq[] = array("En voi l&auml;hett&auml;&auml; yksityisi&auml; viestej&auml;!", "T&auml;h&auml;n on kolme syyt&auml;; et ole rekister&ouml;itynyt/kirjautunut sis&auml;&auml;n, yll&auml;pito on poistanut yksityisviestien k&auml;yt&ouml;n koko j&auml;rjestelm&auml;st&auml; tai yll&auml;pito on est&auml;nyt sinua l&auml;hett&auml;m&auml;st&auml; viestej&auml;. Jos kyse on j&auml;lkimm&auml;isest&auml; tapauksesta, ota yhteys yll&auml;pitoon selvitt&auml;&auml;ksesi syy.");
$faq[] = array("Saan jatkuvasti ei toivottuja yksityisi&auml; viestej&auml;!", "Tulevaisuudessa tulemme lis&auml;&auml;m&auml;&auml;n estolistan yksityisviesteihin. T&auml;ll&auml; hetkell&auml; jos saat ei toivottuja viestej&auml;, ilmoita j&auml;rjestelm&auml;n yll&auml;pidolle, he voivat est&auml;&auml; k&auml;ytt&auml;j&auml;&auml; l&auml;hett&auml;m&auml;st&auml; yksityisviestej&auml;.");
$faq[] = array("Olen saanut roskapostia tai halventavaa s&auml;hk&ouml;postia joltakin t&auml;st&auml; j&auml;rjestelm&auml;st&auml;!", "Olemme pahoillame jos n&auml;in on k&auml;ynyt. J&auml;rjestelm&auml;n s&auml;hk&ouml;postilomake sis&auml;lt&auml;&auml; varotoimia, joilla voidaan yritt&auml;&auml; j&auml;ljitt&auml;&auml; viestin l&auml;hett&auml;j&auml;. Sinun tulee l&auml;hett&auml;&auml; s&auml;hk&ouml;posti yll&auml;pidolle sis&auml;llytt&auml;en t&auml;ydellinen kopio saamastasi s&auml;hk&ouml;postista. Erityisen t&auml;rke&auml;&auml; on sis&auml;llytt&auml;&auml; s&auml;hk&ouml;postin ominaisuuksista otsikkotiedot (n&auml;iss&auml; on yksityiskohtaiset tiedot l&auml;hett&auml;j&auml;st&auml;). Yll&auml;pito voi t&auml;m&auml;n j&auml;lkeen ryhty&auml; toimenpiteisiin.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB 2 aiheet");
$faq[] = array("Kuka on tehnyt t&auml;m&auml;n j&auml;rjestelm&auml;n (ilmoitustaulun)?", "T&auml;m&auml; ohjelmiston (muokkaamattomassa muodossa) on tuottanut ja julkaissut ja copyrightin hallitsija on <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Se on jaettu GNU General Public Licence ehdoin ja on vapaasti levitett&auml;viss&auml;");
$faq[] = array("Miksi ominaisuutta x ei ole?", "T&auml;m&auml;n ohjelmiston on tuottanut ja lisensoinut phpBB Group. Jos mielest&auml;si ominaisuutta tarvitaan, k&auml;y phpbb.com web sivuilla ja tarkista mit&auml; mielt&auml; phpBB Group on. Ole hyv&auml; &auml;l&auml;k&auml; postita pyynt&ouml;j&auml; foorumeihin osoitteessa phpbb.com. Ryhm&auml; k&auml;ytt&auml;&auml; sourceforge sivustoja uusien ominaisuuksien tekoon. Ole hyv&auml; ja lue l&auml;pi foorumit n&auml;hd&auml;ksesi olemmeko jo ottaneet kantaa ominaisuuteen ja noudata sitten sivuilla annettuja ohjeita.");
$faq[] = array("Keneen otan yhteytt&auml; loukkaavista ja/tai laittomista asioista t&auml;ss&auml; j&auml;rjestelm&auml;ss&auml;?", "Sinun tulee ottaa yhteytt&auml; j&auml;rjestelm&auml;n yll&auml;pitoon. Jos et saa selville kuka t&auml;m&auml; on, tulee sinun ottaa yhteytt&auml; jonkin foorumin moderaattoriin ja kysy&auml; h&auml;nelt&auml; kenen puoleen tulee k&auml;&auml;nty&auml;. Jos et viel&auml;k&auml;&auml;n saa vastausta sinun tulee ottaa yhteytt&auml; web osoitteen (domainin) omistajaan (t&auml;m&auml; selvi&auml;&auml; whois kyselyll&auml;) tai jos kyseess&auml; on vapaa j&auml;rjestelm&auml; (esim. yahoo, free.fr, f2s.com, jne.), hallintoon tai turva tms. osastoon ko. palvelussa. Pyyd&auml;mme ottamaan huomioon ettei phpBB Group voi mill&auml;&auml;n lailla kontrolloida, eik&auml; sit&auml; voida mitenk&auml;&auml;n pit&auml;&auml; vastuullisena siit&auml; kuinka, miss&auml; ja kuka t&auml;t&auml; j&auml;rjestelm&auml;&auml; k&auml;ytt&auml;&auml;. On t&auml;ysin turhaa ottaa yhteytt&auml; phpBB Group:iin miss&auml;&auml;n lakiasioissa (vastuu yms.), asioissa jotka eiv&auml;t suoraan liity phpbb.com web sivustoon tai itse phpBB ohjelmaan sellaisenaan. Jos l&auml;het&auml;t s&auml;hk&ouml;postia phpBB Group:lle mist&auml;&auml;n kolmannen osapuolen ohjelmiston k&auml;yt&ouml;st&auml;, voit odottaa lyhytt&auml; vastausta tai j&auml;&auml;d&auml; ilman vastausta kokonaan.");

//
// This ends the FAQ entries
//

?>