<?php
/*************************************************
 *                          lang_faq.php [turkish]
 *                            -------------------
 *   begin                : Wednesday Oct 3, 2001
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_faq.php,v 9.2 2006/02/12 16:02:32 djmaze Exp $
 *
 *
 * Encoding test n-array summation ∑ latin ae with acute ǽ 
 *********************************************************/

/*************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *********************************************************/
//
// Translation by:
//
// Onur Turgay (postexitus)  :: onurturgay@isnet.net.tr :: http://welcome.to/aaal2000
// Erdem Corapcioglu (erdem) :: erdem@smtg.org          :: http://smtg.org
//
// For questions and comments use: onurturgay@isnet.net.tr
//

$faq[] = array("--","Giriş ve Kayıt sorunları");

$faq[] = array("Neden giriş yapamıyorum?", "Kayıt oldunuz mu? Giriş yapabilmek için önceden kayıt olmanız gerek. Yoksa mesaj panosundan banlandınız mı (o halde bu anlamda bir mesaj görmeniz gerekir)? Eğer öyleyse, site yöneticisiyle (webmaster) veya pano yöneticisiyle (administrator) irtibata geçip sebebini sorabilirsiniz. Eğer kayıt olduysanız ve banlanmış olmamanıza rağmen giriş yapamıyorsanız, tekrar tekrar kullanıcı adınızı ve şifrenizi kontrol edin. Genelde hata burada oluyor. Sorun bu değilse pano yöneticisiyle irtibata geçin, belki mesaj panosu için yanlış ayar yapmış olabilir.");
$faq[] = array("Neden kayıt olmam gerekiyor?", "Kayıt olmanıza gerek olmayabilirdi aslında. Mesaj gönderebilmek için kaydın şart olması, pano yöneticisinin (administator) kararına bağlı. Ayrıca kayıt olunca bazı özel imkanlara ulaşabilirsiniz. Örneğin mesajlarınızın yanında kedinize ait küçük bir resim (avatar) gösterme, özel mesaj gönderme, tanıdığınız kullanıcılara mail gönderme veya kullanıcı gruplarına katılma imkanlarına misafir kullanıcılar sahip değildir. Kayıt işlemi çok basit olduğu için kaydolmanız önerilir.");
$faq[] = array("Neden otomatik olarak çıkışım yapılıyor?", "Giriş sayfasında gördüğünüz <i>Her zaman otomatik giriş yap</i> komutunu seçmediğiniz sürece, mesaj panosu sizi sadece belirli bir süre için giriş yapmış kabul eder. Böylece kaydınızın başkaları tarafından kullanılması önlenir. Girişinizin devamlı kalması için, bu komutu seçmeniz yeterlidir. Fakat başka şahıslarında kullandığı (örn. herhangi bir kütüphaneye, internet cafeye, üniversiteye vs. ait) bir bilgisayardan giriş yapıyorsanız, bu komutu seçmemeniz önerilir.");
$faq[] = array("Kimler Online listesinde ismimin görülmesini nasıl önleyebilirim?", "Şahsınıza ait profil sayfasında <i>Online olduğumu gizle</i> seçeneğini bulabilirsiniz. Buradan <i>Evet</i> 'i seçince online olduğunuzu sadece pano yöneticileri ve kendiniz görebilirsiniz. Bu durumda gizli kullanıcı olarak sayılırsınız.");
$faq[] = array("Şifremi unuttum!", "Telaşa kapılmayın! Eski şifrenizi öğrenmek mümkün olmasa bile, yerine değişik bir şifre alabilirsiniz. Giriş sayfasını açıp <u>Şifremi unuttum</u> üzerini tıklayın ve tarif edilen işlemleri uygulayın. Kısa sürede tekrar online olduğunuzu göreceksiniz.");
$faq[] = array("Kayıt oldum ama giriş yapamıyorum!", "İlk önce kullanıcı adınızı ve şifrenizi doğru yazdığınızı temin edin. Doğru yazılmışsa, iki sebep daha olabilir. Eğer COPPA destekleniyorsa ve kaydınız esnasında <u>13 yaşından küçüğüm</u> linkini tıkladıysanız, tarif edilen işlemleri uygulamanız gerek. Sebep bu değilse, kaydınızın onaylanması gerekebilir. Bazı mesaj panoları tüm yeni kayıtların onaylanmasını şart koşar. Giriş yapabilmeniz için ya kendiniz yada pano yöneticisi tarafından kaydınız onaylanmalıdır. Bu durumda onay gerekçesi, kaydınız esnasında size bildirilmiş olmalı. Bu doğrultuda bir e-mail aldıysanız, tarif edilen işlemleri uygulamanız gerek. Eğer böyle bir e-mail almadıysanız, verdiğiniz e-mail adresinin doğru olup olmadığını kontrol edin. Onay gerekçesinin sebebi, <i>kötü amaçlı</i> kullanıcıların anonim kalıp mesaj panosunu suiistimal etmelerini önlemektir. Verdiğiniz e-mail adresinin doğru olduğundan eminseniz, pano yöneticisiyle irtibata geçmeniz gerekir.");
$faq[] = array("Daha önceleri kayıtlıydım ama artık giriş yapamıyorum?!", "Bunun en olası sebebi hatalı kullanıcı adı veya şifre girişidir (kayıt olduktan sonra aldığınız e-maile bakıp kontrol edin). Belkide pano yöneticisi kaydınızı herhangi bir sebepten dolayı silmiş olabilir. Panoya hiç mesaj gönderdinizmi? Veritabanının kapladığı alanı küçük tutmak için, mesaj göndermeyen kullanıcıların kaydı genelde belirli bir süre sonra silinir. Tekrar kaydolmayı deneyin ve tartışmalara katılın.");

$faq[] = array("--","Kullanıcı Seçenekleri ve Ayarları");
$faq[] = array("Kullanıcı ayarlarımı nasıl değiştirebilirim?", "Eğer kaydolduysanız bütün ayarlarınız veritabanına kaydedilir. Ayarlarınızı değiştirmek için (genelde sayfaların üst kısmında bulunan) <u>Profil</u> linkini tıklayın. Ayarlarınız buradan değiştirilir.");
$faq[] = array("Gösterilen saatler yanlış!", "Gösterilen saatler büyük bir ihtimalle doğrudur. Fakat gördüğünüz saat, bulunduğunuz yerin saat diliminden farklı olabilir. Bu durumda, <u>Profil</u> linkini tıklayıp kendiniz için geçerli saat dilimini seçmeniz gerekir, örn. London, Paris, New York, Sydney vs. Çoğu seçenekler için geçerli olduğu gibi, saat dilimini değiştirme imkanıda sadece kayıtlı kullanıcılara verilmiştir. Eğer kayıtlı değilseniz, kaydolmanın tam zamanı (kelime oyununu bağışlayın)!");
$faq[] = array("Değişik bir zaman dilimi seçtim ama saatler hala yanlış!", "Doğru zaman dilimini seçtiğinizden eminseniz ve saat hala yanlış gösteriliyorsa, bunun en olası sebebi günışığından yararlanma değişimleri olabilir. Örn. yaz aylarında görülen saatler, bulunduğunuz ülkenin gerçek saatinden bir saat ileri veya geri olabilir. Mesaj panosu bu değişimleri dikkate almaz.");
$faq[] = array("Konuştuğum lisan listede yok!", "Bunun en olası sebepleri, ya pano yöneticisinin konuştuğunuz lisanı destekleyen uzantıyı kurmuş olmayışı, yada bu panonun konuştuğunuz lisana henüz çevrilmiş olmayışıdır. Pano yöneticilerine başvurup, kendi lisanınızı destekleyen uzantıyı kurmalarını rica edin. Eğer böyle bir uzantı yoksa, panoyu kendi dilinize çevirmekte özgürsünüz. Bu konuda daha geniş bilgi için sayfaların alt kısmında görülen phpBB Group linkini tıklayın.");
$faq[] = array("İsmimin altında resim (avatar) göstermek için ne yapmalıyım?", "Mesajların görüntülendiği sayfalarda kullanıcı adlarının altında iki tür resim görebilirsiniz. Birincisi, kullanıcı derecenizi gösterir ve genelde gönderdiğiniz mesaj sayısına bağlı olarak belirli bir sayıda yıldız veya kare şeklindedir. Bunun altında avatar denen biraz daha büyük bir resim görebilirsiniz. Bu resim genelde kullanıcıya ait ve özeldir. Avatar kullanma imkanını pano yöneticisi saptar. Ayrıca avatar'ların ne şekilde kullanılabileceğinide saptar. Avatar kullanamıyorsanız, pano yöneticisine başvurup bu imkanı ne sebepten iptal ettiğini öğrenebilirsiniz (bunun önemli bir sebebi olduğundan eminiz!)");
$faq[] = array("Kullanıcı derecemi nasıl değiştirebilirim?", "Genelde kullanıcı derecenizi doğrudan değiştirmeniz mümkün değil (kullanıcı derecesi, gönderdiğiniz mesajın yanında bulunan isminizin altında ve kullanıcı profili sayfasında görülür). Çoğu mesaj panosunda kullanıcı dereceleri, gönderilen mesajların sayısını veya yetkili üyeleri belirlemek için kullanılır, örn. yöneticiler veya pano yöneticileri özel bir dereceye sahip olabilir. Lütfen gereksiz yere mesaj gönderipte derecenizi yükseltmeye çalışmayın, elde edeceğiniz tek sonuç, yöneticilerin mesajlarınızın sayısını düşürmesi olacaktır.");
$faq[] = array("Bir kullanıcının mail linkini tıklayınca giriş yapmam isteniyor?", "Panoya ait e-mail formuyla maalesef sadece kayıtlı kullanıcılar mail gönderebiliyor (ayrıca yöneticinin bu işlevi çalıştırması gerek). Bunun sebebi, e-mail sisteminin anonim kullanıcılar tarafından suiistimal edilmesini önlemektir.");

$faq[] = array("--","Mesaj Gönderme");
$faq[] = array("Foruma yeni başlık nasıl gönderilir?", "Çok basit: forumu veya başlığı görüntüleme sayfasında <i>Yeni Başlık Gönder</i> düğmesini tıklayın. Yeni mesaj göndermeden önce kayıt olmanız gerekebilir. Forum ve başlık sayfalarının alt kısmında yapabileceğiniz bütün işlemlerin listesini görebilirsiniz (örn. <i>Bu forumda yeni konular açabilirsiniz</i> vs. gibi).");
$faq[] = array("Mesajlar nasıl değiştirilir veya silinir?", "Pano yöneticisi veya forum yöneticisi olmadığınız sürece, sadece kendinize ait mesajları değiştirebilir veya silebilirsiniz. Gönderdiğiniz bir mesajı <i>Mesajı Değiştir</i> düğmesini tıklayarak değiştirebilirsiniz (bu imkan bazen sadece belirli bir süre için mevcuttur). Mesajınıza birileri cevap göndermişse eğer, mesajınızın altında metni kaç defa değiştirdiğinizi gösteren kısa bir yazı göreceksiniz. Mesajınız henüz yanıtlanmamışsa, bu not görülmez. Ayrıca mesajınız pano yöneticileri veya forum yöneticileri tarafından değiştirilincede bu yazı görülmez (yöneticilerin böyle bir durumda metnin hangi kısmını ne sebepten dolayı değiştirdiklerini yazmaları önerilir). Bir mesaja cevap geldikten sonra normal kullanıcılar tarafından silinemez.");
$faq[] = array("Mesaj altına imza nasıl eklenir?", "Herhangi bir mesaja imzanızı ekleyebilmek için önce <i>Profil</i> sayfanıza girip bir imza hazırlamanız gerek. Daha sonra mesaj gönderme formunun alt kısmındaki <i>İmzamı ekle</i> seçeneğini seçip mesajınıza imzanızı ekleyebilirsiniz. Gönderdiğiniz bütün mesajlara genel bir ayar olarak imzanızın eklenmesini istiyorsanız, <i>Profil</i> sayfasındaki seçeneği tıklayın. Buna rağmen dilediğiniz her mesaj için imzanızın eklenmesini önleyebilirsiniz (mesaj gönderme formunda <i>İmzamı Ekle</i> seçeneğini silmeniz yeterli).");
$faq[] = array("Anket nasıl hazırlanır?", "Anket hazırlamak çok basit: yeni bir başlık gönderirken (veya bir başlığın ilk mesajını değiştirirken - bu tabi yetkinize bağlı), mesaj gönderme formunun altında <i>Anket Ekle</i> formunu göreceksiniz (böyle bir formu göremiyorsanız, anket ekleme yetkiniz yok demektir). Anket sorusunu ve en az iki tane anket şıkkı eklemeniz gerekir. Anket şıkkı eklemek için <i>Bu Şıkkı Ekle</i> düğmesini tıklayın. Ayrıca anketin gösterim süresinide belirleyebilirsiniz, 0 süresiz demektir. Eklenebilecek anket şıklarının sayısı sınırlıdır. Bu sınırı pano yöneticisi belirler.");
$faq[] = array("Bir anket nasıl değiştirilir veya silinir?", "Anketlerde mesajlar gibi sadece gönderen kullanıcı, forum yöneticisi veya pano yöneticisi tarafından değiştirilebilir. Bir anketi değiştirmek için, başlığın ilk mesajını tıklayın (ilgili anket daima bu mesaja bağlıdır). Ankete henüz katılan olmadıysa, hazırlayan kullanıcı tarafından değiştirilebilir veya silinebilir. Ankete katılan olmuşsa, sadece forum ve pano yöneticileri tarafından değiştirilebilir veya silinebilir. Böylece bir süre sonra şıkları değiştirip anket sonuçlarını sapıtma olanağı kalmaz.");
$faq[] = array("Anketlere neden katılamıyorum?", "Anketlere sadece kayıtlı kullanıcılar katılabilir (böylece hile yapma olanağı önlenmiş olur). Eğer kayıt olmanıza rağmen anketlere katılamıyorsanız, gerekli yetkilere sahip değilsiniz demektir.");
$faq[] = array("Bazı forumlara neden ulaşamıyorum?", "Bazı forumlar sadece belirli kullanıcılara veya kullanıcı gruplarına açık olabilir. Mesajları okumak, görüntülemek, göndermek için vs. özel yetki gerekebilir. Bu yetkiyi sadece ilgili forum yöneticisi veya pano yöneticisi verebilir, bu kişilere başvurmalısınız.");

$faq[] = array("--","Biçimlendirme ve Başlık Tipleri");
$faq[] = array("BBCode nedir?", "BBCode HTML'in özel bir uygulamasıdır. Forum'a yazdığınız mesajlarda BBCode kullanabilme imkanını pano yöneticisi saptar. Ayrıca mesaj gönderme formundaki seçenekler sayesinde dilediğiniz mesajlarda BBCode'ı iptal etmeniz mümkündür. BBCode, HTML'e benzer tarzdadır fakat tag'ler &lt; ve &gt; yerine köşeli parantez içine alınır: [ ve ]. Ayrıca nelerin nasıl görüntülendiği daha iyi kontrol edilebilir. BBCode hakkında daha geniş bilgiler için, mesaj gönderme sayfasından ulaşabileceğiniz rehbere bakınız.");
$faq[] = array("HTML kullanabilir miyim?", "Pano yöneticisinin müsaade vermesine bağlıdır, ilgili ayarların tümünü o kontrol eder. Eğer müsaade verilmişse, büyük ihtimalle sadece bazı tag'lerin çalıştığını göreceksiniz. Böyle olması <i>güvenlik</i> içindir. Amaç, pano görüntüsünün bozulmasını veya daha değişik sorunların meydana gelmesini önlemektir. Müsaade verilmiş olsa bile, mesaj gönderme formundaki seçenekler sayesinde dilediğiniz mesajlarda HTML'i iptal etmeniz mümkündür.");
$faq[] = array("Smiley nedir?", "Smiley veya Emoticon, belirli duygu ifadelerini vermek için kullanılan işaretlerdir. Metinde küçük resimler halinde görüntülenir. Örn. :) mutlu, :( ise üzgün anlamındadır. Kullanabileceğiniz smileylerin listesini mesaj gönderme formunda görebilirsiniz. Smileyleri aşırı derecede kullanmamaya özen gösterin, metin yoksa okunmaz hale gelebilir. Bu durumda yönetici smileyleri veya mesajınızı tamamıyla silmeye karar verebilir.");
$faq[] = array("Resim gönderebilir miyim?", "Gönderdiğiniz mesajla beraber resimde görüntülenebilir. Fakat şu anda panoya doğrudan resim göndermek mümkün değildir. Bu yüzden umuma açık bir web serverinde kayıtlı bir resme link vermeniz gerek, örn. http://umuma-acik-server.net/resim.gif. Kendi bilgisayarınızda bulunan bir resme link vermeniz mümkün değil (bilgisayarınız umuma açık bir web serveri olmadığı sürece). Ayrıca, umuma açık olmayan ve sadece şifreyle ulaşılan resimlere link vermek mümkün değildir (örn. hotmail veya yahoo mailboxlarında vs. kayıtlı resimler). Resim görüntülemek için, BBCode'ın [img] tag'ini yada (müsaade verilmişse) HTML kullanabilirsiniz.");
$faq[] = array("Duyuru nedir?", "Duyurular çoğu zaman önemli bilgileri içerir, en kısa zamanda okumanızı öneririz. Duyurular, ilgili forumun her sayfasının başında görülür. Duyuru gönderebilmeniz için bu yetkiye sahip olmanız gerek. Yetkilerinizi ise pano yöneticisi saptar.");
$faq[] = array("Sabit başlıklar nedir?", "Sabit başlıklar, ilgili forumun ilk sayfasında, duyuruların hemen altında görülür. Çoğu zaman önemli bilgileri içerirler, mümkünse okumanızı öneririz. Duyurular için geçerli olduğu gibi, herhangi bir foruma sabit başlık göndermek için gereken yetkileri pano yöneticisi saptar.");
$faq[] = array("Kilitli başlıklar nedir?", "Bu başlıkları forum yöneticisi veya pano yöneticisi kilitler. Kilitli başlıkları yanıtlamak mümkün değildir, içerdikleri anketler otomatik olarak sona erir. Başlıklar birçok nedenlerden dolayı kilitlenmiş olabilir.");

$faq[] = array("--","Kullanıcı Seviyeleri ve Grupları");
$faq[] = array("Pano yöneticileri (administrator) nedir?", "Pano yöneticileri, panonun her bölümünde en çok yetkiye sahip olan şahıslardır. Bu kişiler, panonun hertürlü işlevini kontrol edebilir: müsaade verme, yetkilendirme, kullanıcı banlama, kullanıcı grupları yaratma, forum yöneticisi (moderator) yetkilerini verme vs. Ayrıca bütün forumlarda forum yöneticisi (moderator) yetkilerine sahiptirler.");
$faq[] = array("Forum yöneticileri (moderator) nedir?", "Forum yöneticileri, günlük olarak forumun çalışmasını kontrol eden şahıslar veya gruplardır. Başlıkları değiştirme ve silme yetkisine sahiptirler. Ayrıca yönettikleri forumdaki başlıkları kilitleyebilir, taşıyabilir, silebilir ve bölebilirler. Genelde forum yöneticilerinin görevi, <i>off-topic</i>, yani başlık konusuyla ilgisi olmayan yanıtların veya hakaret ve saldırı niteliğinde metinlerin gönderilmesini önlemektir.");
$faq[] = array("Kullanıcı grupları nedir?", "Kullanıcı grupları, pano yöneticilerinin kullanıcıları grup halinde ayırabilmesi için öngörülen bir yöntemdir. Her kullanıcı (çoğu panolardan farklı olarak) birçok gruba üye olabilir. Bu şekilde pano yöneticileri belirli kullanıcılara rahatlıkla forum yöneticisi yetkilerini veya özel forumlara ulaşma yetkisini vs. verebilir.");
$faq[] = array("Bir kullanıcı grubuna nasıl üye olabilirim?", "Bir kullanıcı grubuna üye olmak için, sayfa başındaki kullanıcı grupları linkini tıklayın. Kullanıcı gruplarının listesini göreceksiniz. Grupların tümü <i>erişime açık</i> olmayabilir, bazıları kilitli veya gizli olabilir. Pano açık ise, ilgili düğmeyi tıklayarak üye olmak için istekte bulunabilirsiniz. İsteğinizin kullanıcı grubu yöneticisi tarafından onaylanması gerek, örneğin isteğinizin nedenini sorabilir. İsteğiniz reddedilirse grup yöneticisini lütfen rahatsız etmeyin, bunun nedenleri olsa gerek.");
$faq[] = array("Bir kullanıcı grubunun yöneticisi olmak için ne yapmam gerek?", "Kullanıcı grupları pano yöneticisi tarafından açılır. Pano yöneticisi aynı zamanda her grubun yöneticisini saptar. Eğer yeni bir kullanıcı grubu açmak istiyorsanız, ilk önce pano yöneticisiyle irtibata geçmeniz gerek, kendisine özel mesaj göndermeyi deneyin.");

$faq[] = array("--","Özel Mesajlar");
$faq[] = array("Özel mesaj gönderemiyorum!", "Bunun üç sebebi olabilir: henüz kayıt olmamış veya giriş yapmamışsınız, veya pano yöneticisi bütün pano için özel mesajları iptal etmiş. Üçüncü olanak ise: pano yöneticisi sizin bu imkanı kullanmanızı önlemiş olabilir, bu durumda kendisine nedenini sormanız gerekir.");
$faq[] = array("İstemediğim özel mesajları almaya devam ediyorum!", "İleride özel mesajlar sistemine belirli kişilerden gelen mesajları iptal etme imkanını ekleyeceğiz. Şimdilik herhangi bir şahıstan istemediğiniz özel mesajlar alıyorsanız, pano yöneticisine başvurun. O herhangi bir kullanıcıyı özel mesaj göndermekten men edebilir.");
$faq[] = array("Bu mesaj panosuna kayıtlı birinden spam mail aldım!", "Üzgünüz. Aslında bu panonun sunduğu email gönderme işlevi bundan korunmak için birçok önlemi almış bulunuyor. Aldığınız spam mailinin bir kopyasını pano yöneticisine gönderin. Özellikle aldığınız emailin başlık kısmını (to (kime), subject (konu) vs.) iletmeyi unutmayın, bu kısımda emaili gönderen kullanıcı hakkında bilgiler bulunur. Pano yöneticisi bu bilgilerle meseleyi takip edebilir.");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB 2'yle ilgili Konular");
$faq[] = array("Bu mesaj panosunu kim yazdı?", "Bu yazılım (değiştirilmemiş haliyle) <a href=\"http://phpbb.com/\" target=\"_blank\">phpBB Group</a> tarafından üretilmiş ve genel dağıtıma çıkarılmıştır. Tüm eser hakları phpBB Group'a aittir. Bu eser, GNU General Public Licence antlaşmasına uygun olarak erişime açılmıştır. Bu antlaşmaya uyma şartıyla ücretsiz dağıtılabilir. Daha detaylı bilgiler için üstteki linki tıklayın.");
$faq[] = array("Aradığım ... özellik neden yok?", "Bu yazılım phpBB Group tarafından yazılmış ve dağıtıma çıkarılmıştır. Eğer herhangi bir özelliğin eksik olduğunu düşünüyorsanız, lütfen phpbb.com sitesini ziyaret edip phpBB Group'un ilgili düşüncelerini öğrenin. Lütfen phpbb.com sitesindeki panoya yazıp yeni bir özellik isteğinde bulunmayın. phpbb Group sourceforge aracılığıyla yeni özellikler ekler. Lütfen ilgili forumları gezip ilk önce phpBB Group'un herhangi bir özellikle ilgili tutumunu öğrenin ve daha sonra burada tarif edilen yöntemle başvuruda bulunun.");
$faq[] = array("Bu panoyla ilgili hukuki sorunlar için veya suiistimal durumunda kime başvurabilirim?", "Pano yöneticisine başvurmanız önerilir. Pano yöneticisinin kim olduğunu öğrenemezseniz, ilk önce forum yöneticilerinden biriyle irtibata geçip, kime yazmanız gerektiğini öğrenin. Herhangi bir yanıt alamadığınız takdirde, site sahibine başvurun (whois aramasıyla sitenin sahibini öğrenebilirsiniz) veya (eğer pano ücretsiz hizmet veren sitelerde çalıştırılıyorsa, örn. yahoo, free.fr, f2s.com vs.) sitenin yönetimine veya suiistimal konularıyla ilgilenen şubesine başvurun. phpBB Group'un bu panonun nasıl, nerede ve kimler tarafından çalıştırıldığını kontrol etmediğini ve herhangi bir şekilde bundan sorumlu olmadığını lütfen dikkate alın. phpbb.com sitesiyle veya phpBB yazılımıyla doğrudan ilgisi olmayan herhangi bir hukuki konuda (ihtiyati tedbir, mali sorumluluk, iftira vs.) phpBB Group'la irtibata geçmek tamamen anlamsızdır. Bu yazılımın herhangi üçüncü şahıslar tarafından kullanımıyla ilgili phpBB Group'a e-mail yazarsanız, çok kısa yada hiç cevap almamayı beklemeniz gerek.");

//
// This ends the FAQ entries
//

