<?php

$desc['documentation'] = 'Soon this module will contain a lot of information';

$desc['html'] = 'The main/core files to run CPG-Nuke';
$desc['html/admin'] = 'Contains all files to administer the CMS';
$desc['html/blocks'] = 'Container to store all side/center blocks';
$desc['html/cache'] = 'Folder to store all cached files &amp; settings';
$desc['html/db'] = 'Stores the database classes';
$desc['html/images'] = 'Folder which contains all globaly used images';
$desc['html/includes'] = 'Holds all global needed files, functions and classes';
$desc['html/install'] = 'Files needed to run the installer properly';
$desc['html/language'] = 'Main language files';
$desc['html/modules'] = 'The actual modules container';
$desc['html/themes'] = 'Holds all page layouts';

$desc['modules'] = 'Additional modules to use in CPG-Nuke';
$desc['languages'] = 'No Longer in Use';
$desc['l10n'] = 'All languages placed in their own sub-directory. CPG-Nuke uses UTF-8 encoding so please check our forums for information on editing these files properly. UTF-8 Encoding not only allows languages to use there own characters but also on the same page with other languages: 
          <span title="Afrikaans">afrikaans</span>,
          <span title="Albanian">Shqip</span>,
          <span title="Arabic">عربي</span>,
          <span title="Bosanski"></span>Bosanski,
          <span title="Brazilian"></span>Brazilian,
          <span title="Bulgarian">Български</span>,
          <span title="Czech">Český</span>,
          <span title="Catala">Català</span>,
          <span title="Chinese">汉语</span>,
          <span title="Danish">Dansk</span>,
          <span title="Dutch">Nederlands</span>,
          <span title="Estonian">Eestlane</span>,
          <span title="Euskara"></span>Euskara,
          <span title="Farsi">پارسى</span>,
          <span title="Finnish">Suomi</span>,
          <span title="French">Français</span>,
          <span title="Galego"></span>Galego,
          <span title="German">Deutsch</span>,
          <span title="Greek">ΕΛΛΗΝΙΚΌΣ</span>,
          <span title="Hungarian">Magyar</span>,
          <span title="Icelandic"></span>Icelandic,
          <span title="Indonesian"></span>Indonesian,
          <span title="Italian">Italiano</span>,
          <span title="Japanese">日本語</span>,
          <span title="Korean">한국의</span>,
          <span title="Kurdish"></span>Kurdish,
          <span title="Latvian">Latvisks</span>,
          <span title="Lithuanian"></span>Lithuanian,
          <span title="Macedonian"></span>Macedonian,
          <span title="Melay"></span>Melay,
          <span title="Norwegian">Norsk</span>,
          <span title="Polish">Polski</span>,
          <span title="Portuguese">Português</span>,
          <span title="Romanian">Română</span>,
          <span title="Russian">РУССКИЙ</span>,
          <span title="Serbian"></span>Serbian,
          <span title="Slovak">Slovenský</span>,
          <span title="Slovenian">Slovenščina</span>,
          <span title="Spanish">Espanõl</span>,
          <span title="Swahili">Kiswahili</span>,
          <span title="Swedish">Svensk</span>,
          <span title="Thai">คนไทย</span>,
          <span title="Turkish">Türk</span>,
          <span title="Uighur"></span>Uighur,
          <span title="Ukrainian"></span>Ukrainian,
          <span title="Vietnamese"></span>Vietnamese. <b>It also allows for scientific notation and many other special characters</b><h3> ≈ ≠ ≤ ≥ ♫ ♠ ♣ ♥ ♦ € ₤ ₪ № ™ ∞</h3><br />';
$desc['l10n/afrikaans'] = '<b>Afrikaans</b>
<br />6,381,000 speakers. A variant of the Dutch spoken by the 17th century colonists, with some lexical and syntactic borrowings from Malay, Bantu languages, Khoisan languages, Portuguese, and other European languages. National language of South Africa';
$desc['l10n/albanian'] = '<b>Albanian</b>
<br />2,900,000 speakers in Albania (1989). 3,202,000 speakers in Albania including Gheg (1989), 98% of the population (1989). Population total all countries 3,000,000 for Tosk, 5,000,000 for all Albanian.
<br />Alternate names: TOSK, ARNAUT, SHKIP, SHQIP, SKCHIP, SHQIPERЁ, ZHGABE.
<br />Dialects: ARBANASI (ZADAR), SREM (SYRMIA), CAMERIJA, KORCA.';
$desc['l10n/arabic'] = 'Region Middle east, north Africa, other Muslim countries. Also spoken in 24 other countries including Algeria, Bahrain, Chad, Comoros Islands, Egypt, Eritrea, Iraq, Israel, Jordan, Kuwait, Lebanon, Libya, Morocco, Oman, Palestinian West Bank and Gaza, Qatar, Somalia, Sudan, Syria.
<br />Alternate names HIGH ARABIC, AL FUS-HA, AL ARABIYA
<br />Dialects MODERN STANDARD ARABIC (MODERN LITERARY ARABIC), CLASSICAL ARABIC (KORANIC ARABIC, QURANIC ARABIC).';

$desc['l10n/basque']='Population 580,000 in Spain (1991 L. Trask U. of Sussex). There are 2,000,000 residents of the 3 provinces of Basque territory; 25% were born outside the territory, 40% in the territory were born to Basque parents. 4,400,000 in Spain have a Basque surname; 19% live in Basque country. Population total all countries 580,000 or more.
<br />Region:: French-Spanish border, 3 Basque provinces: Alava (Araba), Biskaia (Biskay), and Gipuzkoa of the Autonomous Basque Community (CAV); in the northern area of the Autonomous Region of Navarra (Nafarroa) of north central Spain. Also spoken in Australia, Costa Rica, Mexico, Philippines, USA. 
<br />Alternate names VASCUENSE, EUSKERA
<br />Dialects GUIPUZCOAN (GUIPUZCOANO, GIPUZKOAN), ALTO NAVARRO SEPTENTRIONAL (HIGH NAVARRESE, UPPER NAVARRAN), ALTO NAVARRO MERIDIONAL, BISCAYAN (VIZCAINO), AVALAN. 
Batua is based on Guipuzcoan, the central and most widely known dialect. A fair amount of inherent intelligibility among all regional varieties except Souletin. Regional varieties are sometimes preferred for oral use, but in Spain there is also a fairly strong desire for the Batua unified standard. Bilingualism in Castillian, Catalan sometimes. Ages 2 to 20 and over 50 as first language, all ages as first or second language in mainly Basque-speaking areas. Euzkadi is the name of the Basque region, not for the language.';


$desc['l10n/bosanski'] = 'AKA Bosnian 10,200,000 speakers in Yugoslavia and Macedonia (1981). speakers in all countries 21,000,000 (1999).
<br />Region: Serbia, Kossovo, and Montenegro. Also spoken in 23 other countries including Albania, Australia, Austria, Bosnia-Herzegovina, Bulgaria, Canada, Croatia, Germany, Greece, Hungary, Italy, Macedonia, Romania, Russia (Europe), Slovakia, Slovenia, Sweden, Switzerland, Turkey (Europe).
<br />Alternate names SERBIAN, MONTENEGRIN
Dialects CHAKAVIAN, KAJKAVIAN, STOKAVIAN, TORLAKIAN.
<br />Classification: Indo-European, Slavic, South, Western.
Comments Speakers are Serbs, Croatians, Bosnians, Montenegrins';

$desc['l10n/brazilian'] = 'Repùblica Federativa do Brasil. National or official language: Portuguese. 165,851,000 (1998) Brazillian-Portuguese is a dialect of Portuguese.<br />
The number of languages listed for Brazil is 234. Of those, 192 are living languages and 42 are extinct.';

$desc['l10n/bulgarian'] = '7,986,000 speakers in Bulgaria, 85% of the population (1986). speakers in all countries 9,000,000 (1999).
<br />Alternate names: BALGARSKI.
<br />Dialects: PALITYAN (PALITIANI, BOGOMIL).';

$desc['l10n/chinese_simplified'] = 'CHINESE, MANDARIN 867,200,000 speakers in mainland China (1999), 70% of the population, including 8,602,978 Hui (1990 census). Other estimates for Hui are 20,000,000 or more. 1,042,482,187 all Han in China (1990 census). Population total all countries 874,000,000 first language speakers, 1,052,000,000 including second language speakers.';

$desc['l10n/chinese_traditional']='CHINESE, MIN NAN
<br />ISO 639-1: zh
<br />Population 25,725,000 in mainland China (1984), 2.5% of the population, including 1,000,000 Xiamen dialect (1988 census), 6,000,000 Quanzhou dialect (Quanzhoushi Fangyan Zhi). Population total all countries 45,000,000.
<br />Region: Southern Fujian, Guangdong, south Hainan Island, southern Zhejiang, southern Jiangxi provinces. Xiamen is spoken in southern Fujian, Jiangxi, and Taiwan; Hainan dialect in Hainan; Leizhou on the Leizhou peninsula of southwestern Guangdong; Chao-Shan in the far eastern corner of Guangdong in the Chaozhou-Shantou area; Longdu is a dialect island in the area around Zhongshan City and Shaxi in Guangdong south of Guangzhou; Zhenan Min in southeastern Zhejiang Province around Pingyang and Cangnan and on the Zhoushan archipelago of northeastern Zhejiang. Also spoken in Brunei, Indonesia (Java and Bali), Malaysia (Peninsular), Philippines, Singapore, Taiwan, Thailand, USA.

<br />Alternate names SOUTHERN MIN, MINNAN
<br />Dialects XIAMEN (AMOY), LEIZHOU (LEI HUA, LI HUA), CHAO-SHAN (CHOUSHAN), HAINAN (HAINANESE, QIONGWEN HUA, WENCHANG), LONGDU, ZHENAN MIN.
<br />Classification: Sino-Tibetan, Chinese.
<br />Comments Xiamen has subdialects Amoy, Fujian (Fukien, Hokkian, Taiwanese). Amoy is the prestige dialect. Amoy and Taiwanese are easily intelligible to each other. Chao-Shan has subdialects Chaoshou (Chaochow, Chaochow, Teochow, Teochew) and Shantou (Swatow). Chao-Shan, including Swatow, has very difficult intelligibility with Amoy. Sanjiang is somewhat difficult for other dialect speakers. Hainan is quite different from other dialects. Min Nan is the most widely distributed and influential Min variety.';

$desc['l10n/czech']='Population :10,004,800 in Czech Republic (1990 WA). Population total all countries 12,000,000.
<br />Region: Western, Bohemia, Moravia, Silesia. Also spoken in Austria, Bulgaria, Canada, Israel, Poland, Slovakia, Ukraine, USA.
<br />Alternate names CESTINA, BOHEMIAN
<br />Dialects CENTRAL BOHEMIAN, CZECHO-MORAVIAN, HANAK, LACH (YALACH), NORTHEAST BOHEMIAN, SOUTHWEST BOHEMIAN.
<br />Classification: Indo-European, Slavic, West, Czech-Slovak.
<br />Comments All Czech and Slovak dialects are inherently intelligible to each other\'s speakers.';

$desc['l10n/danish']='<b>DANISH. ISO 639-1: 	da</b>
<br />Population 	5,000,000 in Denmark (1980). Population total all countries 5,326,000.
<br />Region:: 	Also spoken in Canada, Germany, Greenland, Norway, Sweden, UAE, USA.
<br />Alternate names   	DANSK, CENTRAL DANISH, SJAELLAND
<br />Classification 	Indo-European, Germanic, North, East Scandinavian, Danish-Swedish, Danish-Bokmal, Danish.
<br />Comments 	See separate entries for Skåne, often called \'Eastern Danish\' and Jutish, often called \'Western Danish\'. Also see Norwegian, Riksmal.';

$desc['l10n/desi'] = '<b>Desi-DECCAN: a language of India ISO 639-2:inc</b>
<br />Population 	10,709,800 (1990). 
<br />Region 	Central Maharashtra, Deccan Plateau.
<br />Alternate names   	DESI, DEKINI, DECCANI
<br />Dialects 	KALVADI (DHARWAR), BIJAPURI.
<br />Classification 	Indo-European, Indo-Iranian, Indo-Aryan, Southern zone, Unclassified.
<br />Comments 	Distinct from Deccan (Dakhini, Mirgan) dialect of Urdu. Arid. Plateau. Muslim.';

$desc['l10n/dutch'] = '13,400,000 speakers in the Netherlands. total speakers in all countries 20,000,000 or more...Also spoken in Aruba, Australia, Belgium, Canada, France, Germany, Indonesia, Israel, Netherlands Antilles, Philippines, Suriname, UAE, USA.
<br/>Alternate names: NEDERLANDS, HOLLANDS.
<br />Dialects: Fries, Drents, Limburgs, Gronings, Haags.';

$desc['l10n/english'] = '341,000,000 first language speakers 508,000,000 including second language speakers. 60% lexical similarity with German, 27% with French, 24% with Russian. National Language USA and UK. Spoken in 105 countries';

$desc['l10n/estonian'] = '953,032 speakers in Estonia out of 963,281 (93%) ethnic group (1989 census). speakers in total all countries 1,100,000. Also spoken in Australia, Canada, Finland, Latvia, Russia (Europe), Sweden, United Kingdom, USA.
<br />Dialects are grouped into three: Northeastern Coastal Estonian (between Tallinn and Narva), North Estonian (island, western, central, and eastern dialects), and South Estonian (Mulgi, Tartu, Vôru). Vôru, Setu (a subdialect of Vôru), and island are clearly distinct from standard Estonian. All the other dialects are assimilated into standard Estonian.
<br />
Those over 60 and under 20 speak little Russian. It is spoken less in rural areas and in southern areas. 75% to 80% of the population in the northeast are Russian speakers. Those over 60 know some German. Most in the north speak Finnish for common topics. Estonian has remained the language of education, including universities. Some linguistic influences from Russian, German, Swedish, Latvian, Lithuanian, and Finnish.';

$desc['l10n/farsi']='Population : 22,000,000 in Iran, or 35.92% of the population (1997), including 800,000 Dari in Khorasan, Gilan, Tat, Bakhtiyari, Lor. Population total all countries 24,280,000.
<br />Region:: Central and south central Iran. Also spoken in 26 other countries including Australia, Austria, Azerbaijan, Bahrain, Canada, Denmark, France, Germany, Greece, India, Iraq, Israel, Netherlands, Oman, Qatar, Saudi Arabia, Spain, Sweden, Tajikistan.
<br />Alternate names PERSIAN, PARSI
<br />Dialects QAZVINI, MAHALLATI, HAMADANI, KASHANI, ISFAHANI, SEDEHI, KERMANI, ARAKI, SHIRAZI, JAHROMI, SHAHRUDI, KAZERUNI, MASHADI (MESHED), BASSERI.
<br />Classification Indo-European, Indo-Iranian, Iranian, Western, Southwestern, Persian.
<br />Comments The literary language is virtually identical in Iran and Afghanistan, with very minor lexical differences. Zargari may be a dialect used by goldsmiths (also see Balkan Romani in Iran). Dialect shading into Dari in Afghanistan and Tajiki in Tajikistan.';

$desc['l10n/finnish'] = '<b>Finnish ISO 639 Code: fin ISO 639-1:	fi</b>
<br />Finland. 4,700,000 in Finland, 93.5% of population (1993), including 30,000 speakers of Tornedalen Finnish. Population total all countries 6,000,000. 
<br />Alternate names: SUOMI, SUOMEA. 
<br />Dialects: SOUTHWESTERN FINNISH, HÄME (TAVAST), SOUTH POHJANMAA, CENTRAL AND NORTH POHJANMAA, PERÄPOHJA, SAVO (SAVOLAX), SOUTHEASTERN FINNISH (FINNISH KARJALA, FINNISH KARELIAN). 
<br />Classification: Uralic, Finno-Ugric, Finno-Permic, Finno-Cheremisic, Finno-Mordvinic, Finno-Lappic, Baltic-Finnic, Finnic.';

$desc['l10n/french'] = 'French : ISO 639-1:	fr
<br />France. 51,000,000 first language speakers in France. Population total all countries 77,000,000 first language speakers, 128,000,000 including second language speakers. 
<br />Alternate names: FRANÇAIS. 
<br />Dialects: STANDARD FRENCH, NORMAN (NORMAND), PICARD (ROUCHI, CHTIMI), WALLON (WALLOON), ANGEVIN, BERRICHON, BOURBONNAIS, BOURGUIGNON, FRANC-COMTOIS, GALLO, LORRAINE, POITEVIN, SANTONGEAIS. 
<br />Classification: Indo-European, Italic, Romance, Italo-Western, Western, Gallo-Iberian, Gallo-Romance, Gallo-Rhaetian, Oïl, French.';

$desc['l10n/galego'] = 'Galego ISO 639-1:	gl
<br />Spain. 3,173,400 in Spain, 8.2% of the population (1986). Population total both countries 4,000,000. 
<br />Alternate names: GALEGO, GALLEGO, Gallegan. 
<br />Classification: Indo-European, Italic, Romance, Italo-Western, Western, Gallo-Iberian, Ibero-Romance, West Iberian, Portuguese-Galician.';

$desc['l10n/german'] = 'GERMAN, STANDARD: a language of Germany ISO 639-1: 	de
<br />Population 	75,300,000 in Germany (1990). Population total all countries 100,000,000 first language speakers; 128,000,000 including second language speakers.
<br />Region 	Also spoken in 40 other countries including Argentina, Australia, Austria, Belgium, Bolivia, Bosnia-Herzegovina, Brazil, Canada, Chile, Czech Republic, Denmark, Ecuador, Estonia, Finland, France, Hungary, Italy, Kazakhstan, Kyrgyzstan.
<br />Alternate names   	DEUTSCH, HOCHDEUTSCH, HIGH GERMAN
<br />Dialects 	ERZGEBIRGISCH.
<br />Classification 	Indo-European, Germanic, West, High German, German, Middle German, East Middle German.
<br />Comments 	Major related language areas are Bavarian, Schwäbisch, Allemannisch, Mainfränkisch, Hessisch, Palatinian, Rheinfränkisch, Westfälisch, Saxonian, Thuringian, Brandenburgisch, and Low Saxon. Many varieties are not inherently intelligible with each other. Our present treatment in this edition is incomplete. Standard German is one High German variety, which developed from the chancery of Saxony, gaining acceptance as the written standard in the 16th and 17th centuries. High German refers to dialects and languages in the upper Rhine region. 60% lexical similarity with English, 29% with French.';

$desc['l10n/greek'] = 'GREEK: a language of Greece ISO 639-1: el
<br />Population 	9,859,850 in Greece, 98.5% of the population (1986). Population total all countries 12,000,000.
<br />Region 	Thoughout the country. Also spoken in 35 other countries including Albania, Armenia, Australia, Austria, Bahamas, Bulgaria, Canada, Congo, Cyprus, DRC, Djibouti, Egypt, France, Georgia, Germany, Hungary, Italy, Jordan, Kazakhstan.
<br />Alternate names   	ELLINIKA, GREC, GRAECAE, ROMAIC, NEO-HELLENIC
<br />Dialects 	KATHAREVOUSA, DIMOTIKI, SARACATSAN.
<br />Classification 	Indo-European, Greek, Attic.';

$desc['l10n/hebrew'] = 'HEBREW: a language of Israel ISO 639-1: he
<br />Population 	4,847,000 in Israel (1998) or 81% of the population (1995). Population total all countries 5,150,000.
<br />Region 	Also spoken in Australia, Canada, Germany, Palestinian West Bank and Gaza, Panama, United Kingdom, USA.
<br />Alternate names   	IVRIT
<br />Dialects 	STANDARD HEBREW (GENERAL ISRAELI, EUROPEANIZED HEBREW), ORIENTAL HEBREW (ARABIZED HEBREW, YEMENITE HEBREW).
<br />Classification 	Afro-Asiatic, Semitic, Central, South, Canaanite.
<br />Comments 	Not a direct offspring from Biblical or other varieties of Ancient Hebrew, but an amalgamation of different Hebrew strata plus intrinsic evolution within the living speech. Some who use it as primary language now in Israel, learned it as their second language originally. Spoken by all Israelis as first or second language.';

$desc['l10n/hebrew'] = 'HUNGARIAN: a language of Hungary ISO 639-1: hu
<br />Population 	10,298,820 in Hungary (1995), 98% of the population (1986). Population total all countries 14,500,000.
<br />Region 	Also spoken in Australia, Austria, Canada, Israel, Romania, Slovakia, Slovenia, Ukraine, USA, Yugoslavia.
<br />Alternate names   	MAGYAR
<br />Dialects 	ALFOLD, WEST DANUBE, DANUBE-TISZA, KING\'S PASS HUNGARIAN, NORTHEAST HUNGARIAN, NORTHWEST HUNGARIAN, SZEKELY, WEST HUNGARIAN.
<br />Classification 	Uralic, Finno-Ugric, Ugric, Hungarian.
<br />Comments 	Closest to Vogul (Mansi) of Russia. \'Magyar\' is the Hungarian name. National language.';

$desc['l10n/icelandic'] = 'ICELANDIC: a language of Iceland ISO 639-1: is
<br />Population 	230,000 in Iceland. Population total all countries 250,000.
<br />Region 	Also spoken in Canada, USA.
<br />Alternate names   	ÍSLENSKA
<br />Classification 	Indo-European, Germanic, North, West Scandinavian.
<br />Comments 	No appreciable dialect differences. Not inherently intelligible with Faroese. National language.';
$desc['l10n/indonesian'] = 'INDONESIAN: a language of Indonesia (Java and Bali) ISO 639-1: 	id
<br />Population 	17,000,000 to 30,000,000 mother tongue speakers; over 140,000,000 second language users with varying levels of speaking and reading proficiency. Population total all countries 17,050,000 to 30,000,000.
<br />Region 	Used in all regions of Indonesia. Also spoken in Netherlands, Philippines, Saudi Arabia, Singapore, USA.
<br />Alternate names   	BAHASA INDONESIA
<br />Classification 	Austronesian, Malayo-Polynesian, Western Malayo-Polynesian, Sundic, Malayic, Malayan, Local Malay.
<br />Comments 	Reported to be modeled on Riau Malay of northeast Sumatra. Has regional variants. Over 80% cognate with Standard Malay';
$desc['l10n/italian'] = 'ITALIAN: a language of Italy ISO 639-1: 	it
<br />Population 	55,000,000 mother tongue speakers, some of whom are native bilinguals of Italian and regional varieties, and some of whom may use Italian as second language. Population total all countries 62,000,000.
<br />Region 	Also spoken in 29 other countries including Argentina, Australia, Belgium, Bosnia-Herzegovina, Brazil, Canada, Croatia, Egypt, Eritrea, France, Germany, Israel, Libya, Liechtenstein, Luxembourg, Paraguay, Philippines, Puerto Rico, San Marino.
<br />Alternate names   	ITALIANO
<br />Dialects 	TUSCAN, ABRUZZESE, PUGLIESE, UMBRIAN, LAZIALE, CENTRAL MARCHIGIANO, CICOLANO-REATINO-AQUILANO, MOLISANO.
<br />Classification 	Indo-European, Italic, Romance, Italo-Western, Italo-Dalmatian.
<br />Comments 	Regional varieties coexist with the standard language; some are inherently unintelligible to speakers of other varieties unless they have learned them. Aquilano, Molisano, and Pugliese are very different from the other Italian \'dialects\'. Piemontese and Sicilian are distinct enough to be separate languages . Venetian and Lombard are also very different (. Neapolitan is reported to be unintelligible to speakers of Standard Italian. Northern varieties are closer to French and Occitan than to standard or southern varieties. 89% lexical similarity with French, 87% with Catalan, 85% with Sardinian, 82% with Spanish, 78% with Rheto-Romance, 77% with Rumanian. Most Italians use varieties along a continuum from standard to regional to local according to what is appropriate. Possibly nearly half the population do not use Standard Italian as mother tongue. Only 2.5% of Italy\'s population could speak standard Italian when it became a unified nation in 1861.';

$desc['l10n/japanese']='Population 121,050,000 in Japan (1985). Population total all countries 125,000,000 first language speakers; 126,000,000 including second language speakers.
<br />Region: Throughout the country. Also spoken in 26 other countries including American Samoa, Argentina, Australia, Belize, Brazil, Canada, Dominican Republic, Germany, Guam, Mexico, Micronesia, Mongolia, New Zealand, Northern Mariana Islands, Palau, Panama, Paraguay, Peru, Philippines.
Dialects WESTERN JAPANESE, EASTERN JAPANESE.';

$desc['l10n/korean']='KOREAN
[KKN] Korea, South. 42,000,000 in South Korea (1986). Population total all countries 78,000,000.
<br />Alternate names: HANGUOHUA, HANGUK MAL.
<br />Dialects: SEOUL (KANGWONDO, KYONGGIDO), CH\'UNGCH\'ONGDO (NORTH CH\'UNGCH\'ONG, SOUTH CH\'UNGCH\'ONG), KYONGSANGDO (NORTH KYONGSANGDO, SOUTH KYONGSANGDO), CHOLLADO (NORTH CHOLLADO, SOUTH CHOLLADO), CHEJU ISLAND.';
$desc['l10n/kurdish']='AKA KURMANJI
<br />Population 3,950,000 first language speakers (1980), out of 6,500,000 in the ethnic group in Turkey (1993 Johnstone). Population total all countries 7,000,000 to 8,000,000.
<br />Region: The majority are in the provinces of Hakkari, Siirt, Mardin, Agri, Diyarbakir, Bitlis, Bingol, Van, Adiyaman, and Mus. Also many in Urfa, Elazig, Kars, Tunceli, Malatya, Erzurum, Karaman Maras, Sivas, Ankara, and other provinces. Also spoken in 25 other countries including Armenia, Australia, Austria, Azerbaijan, Bahrain, Belgium, France, Georgia, Germany, Iran, Iraq, Jordan, Kazakhstan, Kuwait, Kyrgyzstan, Lebanon, Netherlands, Norway, Sweden.
<br />Alternate names NORTHERN KURDISH, KERMANJI, KIRMANJI, KIRDASI, KIRMôNCHA, BôHDINôNI
<br />Dialects GUWII, HAKKôRI, JEZIRE (BOTAN, BOHTôNI, BUHTôNI), URFI, BôYAZIDI, SURCHI, QOCHôNI, BIRJANDI, ALBURZ, SANJôRI, JUDIKôNI.
<br />Differences in speaking among dialects, but all use the same written form.';

$desc['l10n/latvian']='1,394,000 in Latvia including over 500,000 Latgalians. Population total all countries 1,500,000 (1995 V. Zeps).
<br />Alternate names: LATVISKA, LETTISH, LETTISCH.
<br />Dialects: WEST LATVIAN (CENTRAL LATVIAN), EAST LATVIAN (HIGH LATVIAN, LATGALIAN)';

$desc['l10n/lithuanian']='Lithuanian';

$desc['l10n/macedonian']='Macedonian';


$desc['l10n/norwegian'] = 'NORWEGIAN, BOKMAAL 4,250,000 speakers including Nynorsk, 99.5% of population (1991 WA). speakers in all countries 5,000,000 (1999) Also spoken in Canada, Ecuador, Sweden, UAE, USA.
<br />Alternate names BOKMAAL, RIKSMAAL, DANO-NORWEGIAN, NORWEGIAN
<br />Dialects WESTERN NORWEGIAN (COASTAL NORWEGIAN), CENTRAL NORWEGIAN (MIDLAND NORWEGIAN), EASTERN NORWEGIAN (OSTLANDET), NORTHERN NORWEGIAN (TRONDELAAG, NORDLAND). Norwegian form of Danish and based on urban dialects. One of the two norms for written Norwegian. Spoken Norwegian has many dialects, grouped as shown under the dialect list. It was reported in 1971 that 82.5% of the pupils used Riksmaal as their main written language.';

$desc['l10n/polish']='Polish';

$desc['l10n/portuguese']='Portuguese';

$desc['l10n/romanian']='Romanian';

$desc['l10n/russian']='Russian';

$desc['l10n/serbian']='Serbian';
$desc['l10n/slovak']='SLOVAK: a language of Slovakia<br />
<br />ISO 639-1: 	sk
<br />Population 	4,865,450 in Slovakia (1990 WA). Population total all countries 5,606,000.
<br />Region 	Western upland country around Bratislava. Also spoken in Canada, Hungary, Poland, Romania, Ukraine, USA, Yugoslavia.
<br />Alternate names   	SLOVAKIAN
<br />Classification 	Indo-European, Slavic, West, Czech-Slovak.
<br />Comments 	Western and central dialects of Slovak are inherently intelligible with Czech<br /> <br /> ';
$desc['l10n/slovenian']='SLOVENIAN: a language of Slovenia
<br />ISO 639-1: 	sl
<br />Population 	1,727,360 in Slovenia (1991 census). Population total all countries 2,000,000.
<br />Region 	Carniola and southern parts of Styria and Carinthia; Lower Carniola in Dolenjsko, Upper Carniola in Gorenjska, Primorski in West Slovenia, Stajerski in Styria. Also spoken in Argentina, Australia, Austria, Canada, Croatia, Hungary, Italy, USA, Yugoslavia.
<br />Alternate names   	SLOVENSCINA, SLOVENE
<br />Dialects 	LOWER CARNIOLA, UPPER CARNIOLA, STAJERSKI, PRIMORSKI.
<br />Classification 	Indo-European, Slavic, South, Western.
<br />Comments 	The literary dialect is between the two main dialects, based on Dolenjsko. Dialects are diverse.';

$desc['l10n/spanish']='Spanish';

$desc['l10n/swahili']='SWAHILI: a language of Tanzania
<br />ISO 639-1: 	sw
<br />Population 	313,200 monolinguals or 1.8%, 93.4% bilinguals in Tanzania (1982 Polomé). Population total all countries 5,000,000 first language speakers (1989 Holm); 30,000,000 second language users (1989 Holm).
<br />Region 	Zanzibar, coastal areas. Also spoken in Burundi, Kenya, Mayotte, Mozambique, Oman, Rwanda, Somalia, South Africa, Uganda, UAE, USA.
<br />Alternate names   	KISWAHILI, KISUAHELI
<br />Dialects 	MRIMA, UNGUJA (KIUNGUJA, ZANZIBAR), PEMBA, MGAO.
<br />Classification 	Niger-Congo, Atlantic-Congo, Volta-Congo, Benue-Congo, Bantoid, Southern, Narrow Bantu, Central, G, Swahili (G.40).
<br />Comments 	Rural people are second language users; they use the local language for most activities, but Swahili with outsiders. National language.';

$desc['l10n/swedish']='Swedish';
$desc['l10n/tagalog']='Tagalog';
$desc['l10n/thai']='THAI: a language of Thailand
<br />ISO 639-1: 	th
<br />Population 	20,000,000 to 25,000,000 in Thailand (1990 A. Diller), including 400,000 Khorat (1984), 4,704,000 mother tongue Thai speakers who are ethnic Chinese, or 80% of the Chinese (1984). Population total all countries 20,047,000 to 25,000,000.
<br />Region 	Central Thailand, centered in Bangkok. Khorat dialect in Ratchasima. Also spoken in Midway Islands, Singapore, UAE, USA.
<br />Alternate names   	CENTRAL TAI, STANDARD THAI, THAIKLANG, SIAMESE
<br />Dialects 	KHORAT THAI (KORAT).
<br />Classification 	Tai-Kadai, Kam-Tai, Be-Tai, Tai-Sek, Tai, Southwestern, East Central, Chiang Saeng.
<br />Comments 	People sometimes called Siamese.'; 
$desc['l10n/turkish']='TURKISH: a language of Turkey (Asia)
<br />ISO 639-1: 	tr
<br />Population 	46,278,000 in Turkey, 90% of the population (1987). Population total all countries 61,000,000.
<br />Region 	Spoken throughout Turkey as first or second language. Also spoken in 35 other countries including Australia, Austria, Azerbaijan, Belgium, Bosnia-Herzegovina, Bulgaria, Canada, Cyprus, Denmark, El Salvador, Finland, France, Georgia, Germany, Greece, Honduras, Iran, Iraq, Israel.
<br />Alternate names   	TÜRKÇE, TÜRKISCH, ANATOLIAN
<br />Dialects 	DANUBIAN, ESKISEHIR, RAZGRAD, DINLER, RUMELIAN, KARAMANLI, EDIRNE, GAZIANTEP, URFA.
<br />Classification 	Altaic, Turkic, Southern, Turkish.
<br />Comments 	Danubian is western; other dialects are eastern. The Karamanli are Turkish-speaking Greeks. ';
$desc['l10n/ukrainian']='UKRAINIAN: a language of Ukraine
<br />ISO 639-1: 	uk
<br />Population 	31,058,000 in Ukraine (1993), 83% of 37,419,000 in the ethnic group (1993 Johnstone). 75% of the population is ethnic Ukrainian. Population total all countries 47,000,000.
<br />Region 	Western Ukraine, adjacent republics. Also spoken in 25 other countries including Argentina, Armenia, Azerbaijan, Belarus, Brazil, Canada, Estonia, Georgia, Hungary, Kazakhstan, Kyrgyzstan, Latvia, Lithuania, Moldova, Paraguay, Poland, Romania, Russia (Asia), Slovakia.
<br />Dialects 	NORTHWEST UKRAINIAN, SOUTHWEST UKRAINIAN, EAST UKRAINIAN.
<br />Classification 	Indo-European, Slavic, East.
<br />Comments 	Dialect differences are slight.';
$desc['l10n/uighur']='Uighur';
$desc['l10n/ukrainian']='Ukrainian';
$desc['l10n/vietnamese']='VIETNAMESE: a language of Viet Nam
<br />ISO 639-1: 	vi
<br />Population 	65,051,000 in Viet Nam, 86.7% of the population (1993). Population total all countries 68,000,000.
<br />Region 	The entire country. Also spoken in Australia, Cambodia, Canada, China, Côte d\'Ivoire, Finland, France, Germany, Laos, Martinique, Netherlands, New Caledonia, Norway, Philippines, Senegal, Thailand, United Kingdom, USA, Vanuatu.
<br />Alternate names   	KINH, GIN, JING, CHING, VIET, ANNAMESE
<br />Dialects 	NORTHERN VIETNAMESE (TONKINESE, HANOI), CENTRAL VIETNAMESE (HUE), SOUTHERN VIETNAMESE.
<br />Classification 	Austro-Asiatic, Mon-Khmer, Viet-Muong, Vietnamese.
<br />Comments 	Numerous dialects, including the principal ones listed above. People are called \'Kinh.\'';