<?php
/***************************************************************************  
  CPG-Nuke News Theme is released under the terms and conditions 
  of the CPG Open Source License Agreement version 1
  (c) 2004 Akamu Akamai http://cpgnuke.com
  
  $Source: /cvs/themes/CPG-News/coppermine/admin_menu_user.inc,v $
  $Revision: 1.2 $
  $Author: akamu $
  $Date: 2004/11/18 06:49:30 $             
****************************************************************************/
$html = '
    <table cellpadding="0" cellspacing="1">
        <tr>
            <td align="center" width="50%" class="admin_menu"><a href="'.getlink("&amp;file=albmgr").'">'.ALBMGR_LNK.'</a></td>
            <td align="center" width="50%" class="admin_menu"><a href="'.getlink("&amp;file=modifyalb").'">'.MODIFYALB_LNK.'</a></td>
        </tr>
    </table>';
?>